INSERT INTO books (title, description, stock, saleprice, available) VALUES ('Alicia en el pais de las Maravillas', 'Cuento clasico entre la realidad y el sueño', 5, 120, true)
INSERT INTO books (title, description, stock, saleprice, available) VALUES ('El Amor en Los Tiempos Del Colera', 'Compendio acerca del amor y sus múltiples variantes', 2, 150, true)
INSERT INTO books (title, description, stock, saleprice, available) VALUES ('Angeles y Demonios', 'Thriller de teorias de conspiracion', 0, 120, false)
INSERT INTO books (title, description, stock, saleprice, available) VALUES ('Las Aventuras De Sherlock Holmes', 'Relatos detectivescos', 7, 200, true)
INSERT INTO books (title, description, stock, saleprice, available) VALUES ('Las Aventuras De Tom Bombadil', 'Historia del personaje de la comunidad del anillo', 9, 180, true)
INSERT INTO books (title, description, stock, saleprice, available) VALUES ('El beso de la mujer araña', 'Novela de genial simplicidad', 0, 100, false)
INSERT INTO books (title, description, stock, saleprice, available) VALUES ('Cementerio de animales', 'Thriller bestseller', 9, 200, true)
INSERT INTO books (title, description, stock, saleprice, available) VALUES ('Cien Años De Soledad', 'Clasico en su narrativa', 3, 300, true)
INSERT INTO books (title, description, stock, saleprice, available) VALUES ('Cincuenta sombras de Grey', 'Erotico y morboso', 0, 50, false)
INSERT INTO books (title, description, stock, saleprice, available) VALUES ('Luna de Pluton', 'Historia fantastica de ciencia ficcion', 3, 100, true)